sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: wqs926926
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: sky-takeout-114514
    access-key-id: LTAI5tNoNgAHGjcdVBgeTQXz
    access-key-secret: Ik2SG4A6yDFOkhtv55NTpj6kD6SKXP